language: crystal
crystal:
  - latest
  - nightly

script:
  - crystal spec -Dtest -Dswagger -Dwebsocket
  - crystal spec -Dtest -Dswagger -Dwebsocket --release --no-debug
  - crystal tool format --check
  - bin/ameba

matrix:
  allow_failures:
    - crystal: nightly
