language: crystal
crystal:
  - latest
  - nightly

script:
  - shards update --ignore-crystal--version
  - crystal spec -Dtest -Dwebsocket
  - crystal spec -Dtest -Dwebsocket --release --no-debug
  - crystal tool format --check
  - bin/ameba

matrix:
  allow_failures:
    - crystal: nightly
